# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Execute unit tests"
  lane :unit_tests do
    run_tests(devices: ["iPhone 13 pro"],
	      scheme: "TrendingArticlesUnitTests")
  end

  desc "Determine code coverage"
  lane :code_coverage do
    xcov(
      project: "TrendingArticles.xcodeproj",
      scheme: "TrendingArticles",
      output_directory: "xcov_output",
      legacy_support: false)
  end

end
